version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "backend_project.wsgi:application"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  ml_service:
    build: ./ml_service
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
    volumes:
      - ./ml_service:/app
    ports:
      - "8001:8001"